export const GET_CUSTOMER_DETAILS_SUCCESS = 'GET_CUSTOMER_DETAILS_SUCCESS';
export const GET_CUSTOMER_DETAILS_FAILURE = 'GET_CUSTOMER_DETAILS_FAILURE';
export const GET_CUSTOMER_DETAILS_BEGIN = 'GET_CUSTOMER_DETAILS_BEGIN';
